version: '3.8'

services:
  web:
    build: .
    image: aass-api-gateway:latest
    command: pipenv run python ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/aass-api-gateway/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - local
      - aass_network

  db:
    image: postgres:13.0-alpine
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - local

volumes:
  database-data:

networks:
  aass_network:
    name: aass_network
  local:
    driver: bridge
